export interface ClassData {
  id: number;
  title: string;
  days: string;
  startTime: string;
  endTime: string;
  duration: string;
  professor: string;
}

export const dummyClassData: ClassData[] = [
  {
    id: 1,
    title: 'Math 101',
    days: 'Monday, Wednesday',
    startTime: "09:00:00",
    endTime: "10:15:00",
    duration: "1hr 15min",
    professor: 'Dr. Smith',
  },
  {
    id: 2,
    title: 'Math 101',
    days: 'Tuesday, Thursday',
    startTime: '09:00:00',
    endTime: '10:15:00',
    duration: '1hr 15min',
    professor: 'Dr. Smith',
  },
  {
    id: 3,
    title: 'History 202',
    days: 'Tuesday, Thursday',
    startTime: '13:00',
    endTime: '14:15',
    duration: '1hr 15min',
    professor: 'Prof. Johnson',
  },
  {
    id: 4,
    title: 'English 110',
    days: 'Monday, Wednesday',
    startTime: '11:00',
    endTime: '12:15',
    duration: '1hr 15min',
    professor: 'Dr. Brown',
  },
  {
    id: 5,
    title: 'Physics 201',
    days: 'Tuesday, Thursday',
    startTime: '10:30',
    endTime: '11:45',
    duration: '1hr 15min',
    professor: 'Dr. Davis',
  },
  {
    id: 6,
    title: 'Computer Science 301',
    days: 'Monday, Wednesday',
    startTime: '15:30',
    endTime: '16:45',
    duration: '1hr 15min',
    professor: 'Prof. Wilson',
  },
  {
    id: 7,
    title: 'Biology 110',
    days: 'Tuesday, Thursday',
    startTime: '09:00',
    endTime: '10:15',
    duration: '1hr 15min',
    professor: 'Dr. Johnson',
  },
  {
    id: 8,
    title: 'Chemistry 201',
    days: 'Monday, Wednesday',
    startTime: '14:00',
    endTime: '15:15',
    duration: '1hr 15min',
    professor: 'Prof. Adams',
  },
  {
    id: 9,
    title: 'Art History 101',
    days: 'Monday, Wednesday',
    startTime: '10:30',
    endTime: '11:45',
    duration: '1hr 15min',
    professor: 'Dr. Turner',
  },
  {
    id: 10,
    title: 'Economics 202',
    days: 'Tuesday, Thursday',
    startTime: '11:00',
    endTime: '12:15',
    duration: '1hr 15min',
    professor: 'Prof. Miller',
  },
  {
    id: 11,
    title: 'Psychology 101',
    days: 'Monday, Wednesday',
    startTime: '09:00',
    endTime: '10:15',
    duration: '1hr 15min',
    professor: 'Dr. Harris',
  },
  {
    id: 12,
    title: 'Spanish 101',
    days: 'Tuesday, Thursday',
    startTime: '14:00',
    endTime: '15:15',
    duration: '1hr 15min',
    professor: 'Prof. Rodriguez',
  },
  {
    id: 13,
    title: 'Political Science 201',
    days: 'Monday, Wednesday',
    startTime: '15:30',
    endTime: '16:45',
    duration: '1hr 15min',
    professor: 'Dr. Walker',
  },
  {
    id: 14,
    title: 'Geology 101',
    days: 'Tuesday, Thursday',
    startTime: '10:30',
    endTime: '11:45',
    duration: '1hr 15min',
    professor: 'Dr. Turner',
  },
  {
    id: 15,
    title: 'Sociology 202',
    days: 'Monday, Wednesday',
    startTime: '11:00',
    endTime: '12:15',
    duration: '1hr 15min',
    professor: 'Prof. Anderson',
  },
  {
    id: 16,
    title: 'French 101',
    days: 'Tuesday, Thursday',
    startTime: '09:00',
    endTime: '10:15',
    duration: '1hr 15min',
    professor: 'Prof. Martin',
  },
  {
    id: 17,
    title: 'Music 101',
    days: 'Monday, Wednesday',
    startTime: '14:00',
    endTime: '15:15',
    duration: '1hr 15min',
    professor: 'Dr. Brown',
  },
  {
    id: 18,
    title: 'Philosophy 201',
    days: 'Tuesday, Thursday',
    startTime: '15:30',
    endTime: '16:45',
    duration: '1hr 15min',
    professor: 'Prof. Smith',
  },
  {
    id: 19,
    title: 'Physical Education',
    days: 'Monday, Wednesday',
    startTime: '10:30',
    endTime: '11:45',
    duration: '1hr 15min',
    professor: 'Prof. Johnson',
  },
  {
    id: 20,
    title: 'Chemistry 101',
    days: 'Tuesday, Thursday',
    startTime: '11:00',
    endTime: '12:15',
    duration: '1hr 15min',
    professor: 'Dr. Davis',
  },
  {
    id: 21,
    title: 'Literature 201',
    days: 'Monday, Wednesday',
    startTime: '09:00:00',
    endTime: '10:15',
    duration: '1hr 15min',
    professor: 'Prof. Wilson',
  },
  {
    id: 22,
    title: 'Statistics 101',
    days: 'Tuesday, Thursday',
    startTime: '14:00',
    endTime: '15:15',
    duration: '1hr 15min',
    professor: 'Dr. Martinez',
  },
  {
    id: 23,
    title: 'Environmental Science 201',
    days: 'Monday, Wednesday',
    startTime: '15:30',
    endTime: '16:45',
    duration: '1hr 15min',
    professor: 'Prof. Adams',
  },
  {
    id: 24,
    title: 'Theater Arts 101',
    days: 'Tuesday, Thursday',
    startTime: '10:30',
    endTime: '11:45',
    duration: '1hr 15min',
    professor: 'Prof. Kermani'
  }
]
